apiVersion: apps/v1
kind: Deployment
metadata:
  name: asyraf-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-asyraf
  template:
    metadata:
      labels:
        app: my-asyraf
    spec:
      containers:
      - name: my-image
        image: asyraf89/intel1:latest
        ports:
        - containerPort: 8080
