#CICD Workflow

name: CICD
on: push
  
jobs:
  ##build_code##
  build: 
    runs-on: ubuntu-latest
    ##continue-on-error: true
    ##if: github.event_name == 'push'
    steps: 
      - name: close the repository
        ##continue-on-error: true
        uses: actions/checkout@v4.1.2
      - name: setting up java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build the project
        run: mvn package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker image build
        run: |
          docker build -t myapp:latest .
          docker images
      - name: test the image by creating the container
        run: |
          docker run -dt --name web1 myapp:latest
          docker ps -a
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to dockerhub
        run : |
          docker tag myapp:latest asyraf89/intel1:latest
          dokcer push asyraf89/intel1:latest
          
        
      

          
          
